### ISSUE TITLE
Basic CLI to create boards

### ISSUE THREAD

**Issue by sheax0r** [sheax0r/yello#1]
Use stdin:
`cat <file> | yello create <board>`

Read from a file:
`yello create <board> [--file <file>]`

**Comment by mmoghadas** [comment]
Should be able to import from tello as well

**Comment by sheax0r** [comment]
I think you mean this? :) 
https://github.com/sheax0r/yello/issues/6

**Comment by mmoghadas** [comment]
yes sir!
